spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: springcloud-case-config-dev
---
spring:
  profiles: test
  application:
    name: springcloud-case-config-test

